"""
Django settings for donation_system project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""
import os
from pathlib import Path


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY

SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-key',
)

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '[::1]', '.vercel.app']
render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    ALLOWED_HOSTS.append(render_host)
vercel_url = os.getenv('VERCEL_URL')
if vercel_url:
    ALLOWED_HOSTS.append(vercel_url)



INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django REST Framework
    'rest_framework',

    # JWT
    'rest_framework_simplejwt',

    # CORS
    'corsheaders',

    # Our App
    'donor',
    'notifications.apps.NotificationsConfig',
]


MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'donation_system.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'donation_system' / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'donation_system.wsgi.application'



# Database
# Default to SQLite for local development so the app works immediately in a fresh clone.
# Set DB_ENGINE=postgresql and provide DB_* variables to use PostgreSQL instead.
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite3').lower()

if DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'donation_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.getenv('DB_SSLMODE', 'require') if os.getenv('DB_HOST') else 'disable',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]



# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'



# Media files

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



# REST Framework + JWT Authentication

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'donor.authentication.CustomJWTAuthentication',

    ),

}



# JWT Token Settings (optional)

from datetime import timedelta


SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

}
# JWT Token Settings

from datetime import timedelta

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

}


# REST Framework + JWT Authentication

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'donor.authentication.CustomJWTAuthentication',

    ),

}


# ---------------- CORS SETTINGS ----------------

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://0.0.0.0:5173',
    'https://ai-based-donation-management-system-hazel.vercel.app',
]

vercel_url = os.getenv('VERCEL_URL')
if vercel_url:
    CORS_ALLOWED_ORIGINS.append(f'https://{vercel_url}')

render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    CORS_ALLOWED_ORIGINS.append(f'https://{render_host}')

CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://.*\.vercel\.app$',
    r'^https://.*\.onrender\.com$',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://ai-based-donation-management-system-hazel.vercel.app',
    'https://*.vercel.app',
    'https://*.onrender.com',
]

for origin in list(CORS_ALLOWED_ORIGINS):
    if origin.startswith('https://'):
        CSRF_TRUSTED_ORIGINS.append(origin)


CORS_ALLOW_CREDENTIALS = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
